version: "3.7"

x-args: &args
  args:
    UID: ${UID}
    GID: ${GID}


services:
  server:
    build:
      context: ./server
    container_name: app_server
    ports:
      - 8000:8000
    networks:
      app_net:
  python:
    build:
      context: ./python
      <<: *args
    container_name: app_python
    volumes:
      - ./code/python:/home/serveruser/app:delegated
    networks:
      app_net:
  php:
    build:
      context: ./php
      <<: *args
    container_name: app_php
    volumes:
      - ./code/php:/home/serveruser/app:delegated
    networks:
      app_net:
  node:
    build:
      context: ./node
      <<: *args
    container_name: app_node
    volumes:
      - ./code/node:/home/serveruser/app:delegated
    networks:
      app_net:

networks:
  app_net:
